// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzoamuechjzcbzraxslk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6b2FtdWVjaGp6Y2J6cmF4c2xrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNzI3MTYsImV4cCI6MjA3MDY0ODcxNn0.unIjsnfmbI9VV33bFXdFSXjQiFJD0CD8jlf0IhzPM-Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});